### PR TITLE
added decoupler-like API

### PR DESCRIPTION
**Pull request by redst4r**
Hi,

as mentioned, I added a `score_cells.run_gssnng()` method that works with [decouplers](https://github.com/saezlab/decoupler-py) input format (genesets as a simple pandas.DataFrame) and output format (storing scores in adata.obsm['estimate_xyz'].
The function is pretty much a wrapper around the existing code that works with `Genesets` objects for scoring

I had to change the genesets class quite a bit:
- constructor takes lists of genesets now (used to be a .gmt file). Added `genesets_from_gmt()` function to do that instead.
- move some methods out of the class, they were static anyways

There's a new notebook in `notebooks/gssnng_decoupler.ipynb` to showcase the usage. Needs decoupler and omnipath:
```bash
pip install --upgrade decoupler omnipath
```
Maybe we should include that pip command in the notebook too

### CODE REVIEW

**Comment by redst4r** [comment]
btw, I just did a quick comparison of gssnng vs other scoring methods (e.g. simple summing up the counts, or more sophisticated things like AUCell) on the PBMCs (notebooks/gssnng_decoupler.ipynb).

For two scoring methods, I calculate the "score" for each cell with each method and look at the correlation of the scores across cells. Here's the result (each panel is a different geneset/signature):
image

While the three "external" methods seem to correlate reasonably well, gssng is almost uncorrelated. Why is that, am I doing something wrong

-> needs more investigating!

**Comment by Gibbsdavidl** [comment]
Hmm, well gssnng contains ~6 scoring methods.. which are you using?  Want
to send me the function call?

-dave

**Comment by Gibbsdavidl** [comment]
Aucell should be like gssnng “summed_up”

**Comment by redst4r** [comment]
here's how I called gssnng (no particular rationale, I think I copied it from another notebook)

```python
score_cells.run_gssnng(
    adata, model, source='source',target='target', weight='weight',
    groupby=None, # "louvain",
    smooth_mode='connectivity',
    recompute_neighbors=0,
    score_method="singscore",
    method_params={'normalization':'theoretical'},
    samp_neighbors=0,
    ranked=True,
    cores=6
)
```
I tried to disable any sampling, and no splitting into clusters (groupby) to make it as comparable as possible to the other methods

**Comment by Gibbsdavidl** [comment]
I’ll check this out today, thanks!! I found the new notebook.

**Comment by redst4r** [comment]
It's complicated! My comparison to decoupler was too naive:

1. gssnng uses `adata.X`, whereas decoupler (usually) uses `adata.raw.X`. For the PBMCs thats a huge difference (2k genes vs 13k genes)
2. I used gssnng with ranks (even for `summed_up`)
3. The smoothing itself makes quite  a bit of a difference

I'll try to tease apart the effects of those. For starters, I'll try to make gssnng as similar as possible to the existing methods, adding complexity (smoothing, sampling) in one by one. I'll update the notebook tomorrow

**Comment by Gibbsdavidl** [comment]
I tried the summed up method, grouped on cluster, and for TRAIL, it agreed
well with the others.

**Comment by redst4r** [comment]
> I tried the summed up method, grouped on cluster, and for TRAIL, it agreed
yeah, summed_up is pretty consistent (it better should, thats as simple as it gets)

I've been playing around with GSEA today, what a mess :)  3 different implementations, 3 different answers:
- the ssGSEA implementation in gssnng
- my own ssGSEA implementation
- decoupler's GSEA version

Some people report the "integral" of the two ECDFs, others the maximum difference... And it makes a difference if you filter out genes not expressed anywhere.
Couldn't get any consistent  results yet

**Comment by redst4r** [comment]
made some progress on the GSEA discrepancies:
1. There's some odd behavior in ssgsea(), see #20 
2. Gene filtering is a bit unpredictable in gssnng and the total number of genes (in and outside of a geneset) matter.

About 2): There's some unexpected (to me at least) way of how data is sent to those scoring functions in gssnng. In particular its about `score_cell_data._get_cell_data()`. That function takes the smoothed expression matrix and pulls out a single cell's expression vector as a `pd.DataFrame`. But it also **filters out** any non-expressed genes (zero counts) in that cell. This dataframe is then fed to the scoring function.

Here's the filtering code:
```python
gene_mat = (smoothed_adata.obsm['X_smooth'])[cell_ix]
# then we subset it to only the genes with counts
_, gdx, _ = sparse.find(gene_mat)

if gene_mat.ndim == 2:
    df = pd.DataFrame(gene_mat[:, gdx].A.flatten(), index=smoothed_adata.var.index[gdx])  ## ????
```


Here's the problem with that:
1. In the scoring function, we now have no idea how big the **"universe" of genes** is: GSEA computes this running sum for genes in the set, but also for genes *outside* the set (which we now dont have access too). One can use the dataframes `.len()` as a substitute (not fully correct of course).
2. The scoring function receives an expression pd.DataFrame with **different length/#genes for each cell** due to the above filtering of non-expressed genes. Hence, we can't even compare the scores of individual cells (they all use a different background set)

Filtering away the non-expressed genes is probably done to keep memory low, but it creates this problem.

I don't really know an easy way to fix this atm (anything short of disabling that filtering altogether). We could wrap this dataframe into its own class, `SparseExpressionVector`, where we keep track of the the expressed genes (in the dataframe) and the universe of all genes in a separate variable and pass that into the scoring functions. But it might get pretty ugly, as it carries into the scoring functions

**Comment by redst4r** [comment]
But overall, if I fix 1) and 2) I get consistent results with GSEA scoring in gssnng and decoupler. We're on the right track!

**Review by Gibbsdavidl — APPROVED** [review]

**Pull request merged**
